### ライブラリ

- ライブラリとは、再利用しやすいように複数の関数をまとめたもの
- まずは、mathという様々な数学関数を呼び出せるライブラリを使用

In [ ]:
import math

In [ ]:
# 平方根
math.sqrt(3)

1.7320508075688772

In [ ]:
# モジュールに含まれる関数やクラス、定数などに関する説明や使用方法が表示される
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
      

#### math.関数名のリスト

- math.sin(x) : サイン関数
- math.cos(x) : コサイン関数
- math.factorial(x) : 階乗
- math.sqrt(x): 平方根

In [ ]:
# sin. cos
math.sin(10)

-0.5440211108893698

In [ ]:
math.cos(2)

-0.4161468365471424

In [ ]:
# 3! = 3 × 2 × 1, 階乗
math.factorial(3)

6

In [ ]:
# 平方根
math.sqrt(10)

3.1622776601683795

#### ライブラリの読み込みを短縮する

In [ ]:
# 'm'という名前でライブラリを使用
import math as m
m.sqrt(3)

1.7320508075688772

### ライブラリのインストール

- pip 〇〇で、ライブラリを管理するツールを使用出来る。
- まずはOSコマンドを(!)で呼び出し、インストールのリストを見る

In [ ]:
# これだけのライブラリがインストールされている
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.8.5
aiosignal                        1.3.1
alabaster                        0.7.13
albumentations                   1.3.1
altair                           4.2.2
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array-record                     0.4.1
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
attrs                            23.1.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.13.0
backcall                         0.2.0
beautifulsoup4                   4.11.2
bleach                           6.0.0
blinker                          1.4
bl

In [ ]:
# pip install ○○でライブラリをインストールできる

### 便利なライブラリ

- numpy: ベクトルや行列などの数値演算を行うことができる
- pandas: 表形式のデータを柔軟に操作・処理することができる、エクセル内でできることは代替可能
- matplotlib, seaborn, plotly: 柔軟な可視化を行うことができる

#### Numpy

In [ ]:
# asの後のnpは、省略形。今後npで使用できる
import numpy as np

In [ ]:
# 1次元配列の作り方
# listと近い
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [ ]:
# 2次元配列の作り方
# 今回は2行4列の配列を定義
arr2 = np.array([[1, 2, 3, 4], [3, 7, 8, 9]])
print(arr2)

[[1 2 3 4]
 [3 7 8 9]]


In [ ]:
# .T で転置
arr2.T

array([[1, 3],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
# 要素のアクセスは、インデックスを指定
arr2[1]

array([3, 7, 8, 9])

In [ ]:
# 例えばarr2[0][0]は1行目の1列目の要素を取得する事になる
arr2[1][2]

8

#### Pandas

In [ ]:
# エクセルでできるようなことは Pandas で代替可能
import pandas as pd

In [ ]:
# read_csv の結果を dfという変数に格納
# dfという変数に対して様々な処理が可能

df = pd.read_csv("/content/sample教材.csv")
df

年齢    趣味   名前
0   55   テニス  ヤマダ
1   56    野球  マツダ
2   57  サッカー  サナダ
3   58   バスケ  カナダ
4   59   テニス  ヤマダ
5   60    野球  マツダ
6   61  サッカー  サナダ
7   62   バスケ  カナダ
8   63   テニス  ヤマダ
9   64    野球  マツダ
10  65  サッカー  サナダ
11  66   バスケ  カナダ
12  67   テニス  ヤマダ
13  68    野球  マツダ
14  69  サッカー  サナダ
15  70   バスケ  カナダ
16  71   テニス  ヤマダ
17  72    野球  マツダ
18  73  サッカー  サナダ
19  74   バスケ  カナダ

In [ ]:
# numpyと同様にデータの次元を取得できる(20列、3行)
df.shape

(20, 3)

In [ ]:
# 年齢列を抽出
df['年齢']

0     55
1     56
2     57
3     58
4     59
5     60
6     61
7     62
8     63
9     64
10    65
11    66
12    67
13    68
14    69
15    70
16    71
17    72
18    73
19    74
Name: 年齢, dtype: int64

* 行番号や列番号を指定して抽出したい場合は、ilocを使う


In [ ]:
# indexが2の行（3行目）の抽出
df.iloc[2]

年齢      57
趣味    サッカー
名前     サナダ
Name: 2, dtype: object

In [ ]:
# indexが2の行以降（3行目以降）の抽出
df.iloc[2:]

年齢    趣味   名前
2   57  サッカー  サナダ
3   58   バスケ  カナダ
4   59   テニス  ヤマダ
5   60    野球  マツダ
6   61  サッカー  サナダ
7   62   バスケ  カナダ
8   63   テニス  ヤマダ
9   64    野球  マツダ
10  65  サッカー  サナダ
11  66   バスケ  カナダ
12  67   テニス  ヤマダ
13  68    野球  マツダ
14  69  サッカー  サナダ
15  70   バスケ  カナダ
16  71   テニス  ヤマダ
17  72    野球  マツダ
18  73  サッカー  サナダ
19  74   バスケ  カナダ

In [ ]:
# 2列目2行目をピックアップ。0、0で1列目1行目
df.iloc[1, 1]

'野球'

In [ ]:
# 3行目～6行目の1列目～2列目を取得
df.iloc[2:6, 0:2]

年齢    趣味
2  57  サッカー
3  58   バスケ
4  59   テニス
5  60    野球

*   describe()⇒各カラムの平均値や標準誤差、四分位数といった基礎統計量を求めることができる
*   to_csv(): csvファイル形式での保存ができる
*   リスト項目

In [ ]:
df['年齢'].mean()

64.5

In [ ]:
df['年齢'].sum()

1290

In [ ]:
df.describe()

年齢
count  20.00000
mean   64.50000
std     5.91608
min    55.00000
25%    59.75000
50%    64.50000
75%    69.25000
max    74.00000

In [ ]:
# 新しい df2という変数に代入
df2 = df.describe()
df2

年齢
count  20.00000
mean   64.50000
std     5.91608
min    55.00000
25%    59.75000
50%    64.50000
75%    69.25000
max    74.00000

In [ ]:
# dfはデータフレーム
# データの保存
df2.to_csv('sample教材2.csv')